project:
  title: "Hand-in 1"
  type: book
  output-dir: _site
  
website: 
  navbar: 
    left:
      - href: index.qmd
      - text: Home
      - href: prac1.qmd
      - text: Second page
      - href: prac2.qmd
      - text: Third page
      - href: prac-day-four.qmd
      - text: Fourth page

book: 
  chapters: 
    - index.qmd
    - prac1.qmd
    - prac2.qmd
    - prac-day-four.qmd
  
  
format:
  html:
    toc: true
    toc-depth: 3
  
editor: visual

